version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/rust

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: circleci-builder
          POSTGRES_PASSWORD: password
          POSTGRES_DB: calendar

    working_directory: /home/circleci/calendar/
    
    steps:
      - checkout
      - run:
          name: check directory
          command: ls && pwd
          working_directory: ~/calendar/backend
      - run:
          name: rustup version
          command: rustup --version
      - run:
          name: rustup component add
          command: rustup component add clippy rustfmt
      - run:
          name: Format rust codes
          command: cargo fmt -- --check
          working_directory: ~/calendar/backend
      - run:
          name: Build cargo project
          command: cargo build
          working_directory: ~/calendar/backend
      - run:
          name: Install diesel command
          command: cargo install diesel_cli
      - run:
          name: Setup .env file
          command: echo "DATABASE_URL=postgres://circleci-builder:password@postgres:5432/calendar" > .env
          working_directory: ~/calendar/backend
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: Setup diesel
          command: diesel setup
          environment:
            DATABASE_URL: postgres://circleci-builder:password@localhost:5432/calendar?sslmode=disable
          working_directory: ~/calendar/backend
      - run:
          name: Migration
          command: diesel migration generate calendar
          working_directory: ~/calendar/backend
      - run:
          name: lint
          command: cargo clippy -- -D warnings
          working_directory: ~/calendar/backend
      - run:
          name: Run unit tests
          command: cargo test
          environment:
            DATABASE_URL: postgres://circleci-builder:i_love_rust@localhost:5432/calendar?sslmode=disable
          working_directory: ~/calendar/backend
