version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/rust

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: /home/circleci/calendar/
    steps:
      - checkout
      - run:
          name: check directory
          command: ls && pwd
          working_directory: ~/calendar/backend
      - run:
          name: rustup version
          command: rustup --version
      - run:
          name: rustup component add
          command: rustup component add clippy rustfmt
      - run:
          name: fmt
          command: cargo fmt -- --check
          working_directory: ~/calendar/backend
      - run:
          name: build
          command: cargo build
          working_directory: ~/calendar/backend
#      - run:
#          name: lint
#          command: cargo clippy -- -D warnings
#          working_directory: ~/calendar/backend
      - run:
          name: test
          command: cargo test
          working_directory: ~/calendar/backend
